### PR TITLE
Add support for searching against files

### PR DESCRIPTION
**Pull request by kjaym**
This adds the query and result classes for searching against files on Citrination. Results can be highlighted using `FileReturningQuery.setMaxContentHighlights(val)` where  `val` is greater than 0.

There are also a couple very minor documentation fixes thrown in.

### CODE REVIEW

**Comment by sparadiso** [comment]
I have a general thought about a pattern not introduced in this PR (but is being reinforced). There is currently nothing constraining the behavior of `*SearchHit` `*SearchResult` classes - they just indicate intended behavior based on a naming convention. 

Does it make sense to start thinking about common behavior across these classes? For example, I could imagine supporting some guaranteed behavior such as the ability to iterate over `SearchResult`, even if each effective element (a `SearchHit`) is of a different type. Similarly, the ability to append hits to a `SearchResult` (e.g., during pagination) would be nice. That's pretty spitball, but is there a reason we don't do anything like this?

**Comment by kjaym** [comment]
@sparadiso We do that for `*SearchResult` https://github.com/CitrineInformatics/java-citrination-client/pull/68/files#diff-2cda809091fe1af897746849d70adb62. None of the child classes of `BaseSearchResult` actually implement any new behavior. 

We could do that for `*SearchHit` but there isn't a whole lot of overlap other than the fact that they all contain a score and a last updated time.

**Comment by sparadiso** [comment]
Oh, apologize - I did not realize that about BaseSearchResult. I could definitely get rid of some code in CMC... I assume the responses we get back from CSL and the ruby proxy are structured the same?

**Comment by kjaym** [comment]
They are wrapped in a "results" field by the web server, but we unwrap them in this package ... so, yes. https://github.com/CitrineInformatics/java-citrination-client/blob/master/src/main/java/io/citrine/jcc/core/CitrinationClient.java#L297-L308

**Pull request merged**
