### PR TITLE
Simplify and unify query language

### PR DESCRIPTION
**Pull request by kjaym**
@sparadiso @maxhutch This looks like a lot but it is almost completely boilerplate. The significant points follow. This is in support of this card https://trello.com/c/SJpbaRdu.

There are two important changes here. The first, and most important, is that a single query type is defined for any operations that act on datasets or the records that they contain. This unifies the PifQuery and DatasetQuery operations. The new class is io.citrine.jcc.search.core.query.BaseDatasetQuery. The derived classes, which replace PifQuery and DatasetQuery, are PifReturningQuery and DatasetReturningQuery. These new classes do not define any new filtering capabilities, but just contain additional formatting or metadata options specific to the types of records that they return. Overall, this provides a consistent interface, regardless of whether PIFs or datasets are being returned, to filter by dataset ID, PIF ID, dataset metadata content, or PIF content.

The second change is that the method names and types are unified throughout the package. There were some differences in the way that getters, setters, and other similar methods were named between the query language and results objects.

Compatibility notes:
* Making queries from an old JCC/PyCC version: Completely supported without change by user.
* Making queries from this version: Will only work against sites that support this version (none yet).
* Java code: If a user upgrades to JCC 2.x, then they will have to change their code to use the new classes. But to the first bullet, their code will continue to execute properly against the APIs if they don't change versions.

### CODE REVIEW

**Comment by maxhutch** [comment]
I don't understand the motivation for differentiating `PifReturningQuery` and `DatasetReturningQuery`.  They look to be nearly identical.  Could they be more fully unified by ignoring components based on the endpoint they are sent to and/or composition?

**Comment by kjaym** [comment]
@maxhutch They are close in components at the moment but I think there are two reasons to keep them separate: 

1. I don't like the idea of fields being present when they have no effect. 
2. These two classes will certainly diverge more over time. I'd rather have people lock in on them now than switch it up later.

**Comment by maxhutch** [comment]
Is it accurate to say this is not actually unifying the queries, so much as we are giving them a common parent?  A user will still need to define separate queries for datasets and pifs, which seems unnecessary.

**Comment by kjaym** [comment]
It is unifying the query parts (filtering by IDs or content), which is the goal. I want it to be that the way that you ask for data does not change. But it does make sense to me that you would have some context-specific options depending on what you are getting back.

**Comment by kjaym** [comment]
@sparadiso @maxhutch Any other thoughts?

**Comment by maxhutch** [comment]
> I want it to be that the way that you ask for data does not change.

What do you mean by that?  If it is what I think it is (different query objects for different query actions), you could still use composition to make the code more lightweight.  It seems strange that a "unification" results in 1200 more lines of code.

**Comment by kjaym** [comment]
@maxhutch Finally circling back on this. 

```
What do you mean by that? If it is what I think it is (different query objects for different query actions), you could still use composition to make the code more lightweight.
```
Your interpretation is correct. The reason that this looks heavy, I think, is because I have to override `return this` from each subclass. I am thinking more about the way that the query looks when serialized than the class hierarchy as implemented in java (for example, the python implementation of this will be very lightweight). 

The title of this PR might be a misnomer. The actual result is a more complete query language. I am pushing out an additional change right now that adds an additional level of control - a root level list of queries against any combination of dataset IDs, metadata, PIF IDs, or PIF content.

**Comment by sparadiso** [comment]
Are we planning on circling back on this PR? @kjaym @maxhutch

**Comment by kjaym** [comment]
@sparadiso Absolutely. This is required for collections.

**Comment by maxhutch** [comment]
@kjaym I voiced my high level thoughts before.  Is there actual code you'd like us to get eyes on?  The PR is so large my browser won't even render most of the diffs, so some guidance would be helpful.

Can we kill the codeship tests?

**Comment by kjaym** [comment]
@maxhutch I will look into getting codeship to stop running. They changed their interface and I can't find the delete button anymore.

The only code that has any kind of complicated logic is the backwards compatibility for deserialization of queries from v1.x of this library. That will let users continue to use old libraries to make requests and still get the same results as someone running v2.x. There are a couple tests for this... [PifSystemReturningQueryTest](src/test/java/io/citrine/jcc/search/pif/query/PifSystemReturningQueryTest.java) which deserializes an old [PifQuery](src/test/resources/pifQuery.json) and [DatasetReturningQueryTest](src/test/java/io/citrine/jcc/search/pif/query/DatasetReturningQueryTest.java) which deserializes an old [DatasetQuery](src/test/resources/datasetQuery.json). 

These new queries have the following general structure:

```
{
  settings...
  "query": [{
    "logic": logic to use,
    "dataset": [{ query against dataset }],
    "system": [{ query against PIF system }]
  }]
}
```

All queries now have this structure. The difference between a PifSystemReturningQuery and DatasetReturningQuery is the `settings` block at the top of the query. That contains things like pagination information and formatting of results. The query block is exactly the same for these two types of queries. This lets us return PIFs (or datasets) by the content of a dataset and/or content of PIFs. 

For reference, this is a query for a PIF in the old syntax:

```
{
  "from": 10,
  "size": 100,
  "randomResults": true,
  "randomSeed": 0,
  "returnSystem": false,
  "addLatex": true,
  "scoreRelevance": true,
  "includeDatasets": [1],
  "excludeDatasets": [2],
  "system": [{
    "names": {
      "filter": {"equal": "lithium"}
    }
  },{
    "chemicalFormula": {
      "filter": {"equal": "Li"}
    }
  }]
}
```

that has the following structure in the new one:

```
{
  "size" : 100,
  "returnSystem" : false,
  "addLatex" : true,
  "fromIndex" : 10,
  "randomResults" : true,
  "randomSeed" : 0,
  "scoreRelevance" : true,
  "query" : [ {
    "logic" : "MUST",
    "dataset" : [ {
      "id" : [ {
        "equal" : "1"
      } ]
    } ]
  }, {
    "logic" : "MUST_NOT",
    "dataset" : [ {
      "id" : [ {
        "equal" : "2"
      } ]
    } ]
  }, {
    "logic" : "MUST",
    "system" : [ {
      "names" : [ {
        "filter" : [ {
          "equal" : "lithium"
        } ]
      } ]
    }, {
      "chemicalFormula" : [ {
        "filter" : [ {
          "equal" : "Li"
        } ]
      } ]
    } ]
  } ]
}
```

**Comment by sparadiso** [comment]
Broadly speaking, I think the structure of the query is more intuitive now 👍 . Given that this PR is too big to comprehensively review, could we stake out some time to kick the tires on stage before pulling it into master? I'd like to see that query results against the same database are identical using 1.x and 2.0 queries, etc.

**Comment by kjaym** [comment]
@sparadiso Good point. I am going to close this and open against a different branch.

**Pull request closed without merging**
